function [irfsOBC,irfsNoBounds,IRFoffset] = extract_irfs_dynareOBC( dynareOBC_, oo_, varNames, shockNames )
% This function extracts IRFs generated from dynareOBC simulations.
%
% Inputs:
%   - dynareOBC_    Output generated by dynareOBC
%   - oo_           Output generated by Dynare (stoch_simul command)
%   - varNames      [v x 1] char array with the v variable names of interest
%   - shockNames 	[s x 1] char array with the s shock names of interest
%
% Outputs:
%   - irfsOBC       [structure] IRFs with bounds imposed, in level deviation
%   - irfsNoBounds  [structure] IRFs with no bounds imposed, in level deviation
%   - IRFoffset     [structure] Level to be added to the IRFs for levels
%                   (point of reference, often equal to the steady state)
%
% C. Cantore and P. Meichtry, based on code by J. Swarbrick, September 2024
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

nshocks = size(shockNames,1);
nvars = size(varNames,1);

for j=1:nshocks
    for i=1:nvars
        VarName = strtrim( varNames(i,:) );
        ShockName = strtrim( shockNames(j,:) );
        
        irfsOBC.(VarName).(ShockName) = oo_.irfs.([VarName,'_',ShockName]);
        irfsNoBounds.(VarName).(ShockName) = dynareOBC_.IRFsWithoutBounds.([VarName,'_',ShockName]);
        IRFoffset.(VarName).(ShockName) = dynareOBC_.IRFOffsets.([VarName,'_',ShockName]);
    end
end

end
